-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.blogs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    publish_date timestamp with time zone NOT NULL DEFAULT now(),
    update_date timestamp with time zone,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    thumbnail text COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default" NOT NULL,
    slug text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    published boolean NOT NULL DEFAULT false,
    CONSTRAINT blog_pkey PRIMARY KEY (id),
    CONSTRAINT blog_slug_key UNIQUE (slug)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.blogs
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.blogs
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.blogs TO anon;

GRANT ALL ON TABLE public.blogs TO postgres;

GRANT ALL ON TABLE public.blogs TO supabase_admin;

GRANT ALL ON TABLE public.blogs TO authenticated;

GRANT ALL ON TABLE public.blogs TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.blogs
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

DROP FUNCTION IF EXISTS graphql.build_insert(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text);

DROP FUNCTION IF EXISTS graphql.build_update(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text, parent_block_name text);

DROP FUNCTION IF EXISTS graphql.cache_key(role regrole, ast jsonb, variables jsonb);

DROP FUNCTION IF EXISTS graphql.build_delete(ast jsonb, variable_definitions jsonb, variables jsonb, parent_type text, parent_block_name text);

DROP TABLE IF EXISTS graphql._field CASCADE;

DROP TABLE IF EXISTS graphql._type CASCADE;
